# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Gas Tracker' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Gas Tracker
  pod 'lottie-ios'
  pod 'Charts'
  target 'Gas TrackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Gas TrackerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
